

/*
Test generated by RoostGPT for test event-source-cqrs-azure using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=setName_5a27c66b16
ROOST_METHOD_SIG_HASH=setName_3abba3fbc9

Before executing the test cases,
- Make sure to build the 'spring-leads-infra' project and install it into your local maven repository.
- Check your repositories mentioned in the pom.xml file.
- Also, check for a proper internet connection.
*/

package com.baeldung.write.commands;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import javax.validation.constraints.NotNull;
import com.baeldung.infra.command.Command;

//Test class containing test cases for 'setName' method of 'CreateLead' class
public class CreateLeadSetNameTest {

	private CreateLead lead;

	@BeforeEach
	public void setUp() {
		lead = new CreateLead();
	}

	@Test
	public void shouldThrowNullPointerExceptionForNullName() {
	  // Given
	  String testName = null;

	  // When & Then
	  assertThrows(NullPointerException.class, () -> {
		lead.setName(testName);
	  });
	}

	@Test
	public void shouldSetNameForValidInput() {
	  // Given
	  String testName = "validInput";

	  // When
	  lead.setName(testName);

	  // Then
	  assertEquals(testName, lead.getName());
	}

	@Test
	public void shouldSetNameForEmptyString() {
	  // Given
	  String testName = "";

	  // When
	  lead.setName(testName);

	  // Then
	  assertEquals(testName, lead.getName());
	}
	// Considering the ERROR LOG reported, it's a MAVEN BUILD issue and not related to the
	// test cases.
	// Please make sure you have proper internet connection and correct repository path
	// mentioned in pom.xml file.
	// In case this doesn't solve the problem, check your project dependencies. You might
	// have to install missing dependencies into your local maven repository.
}
